// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductList.Api.Infrastructure.Persistence;

#nullable disable

namespace ProductList.Api.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260424204334_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductList.Api.Features.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRD-001",
                            Name = "Whole Bean Coffee",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            Code = "PRD-002",
                            Name = "Black Leaf Tea",
                            Price = 24.50m
                        },
                        new
                        {
                            Id = 3,
                            Code = "PRD-003",
                            Name = "Dark Chocolate 70%",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 4,
                            Code = "PRD-004",
                            Name = "Multiflower Honey 500g",
                            Price = 34.00m
                        },
                        new
                        {
                            Id = 5,
                            Code = "PRD-005",
                            Name = "Extra Virgin Olive Oil",
                            Price = 59.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
